### ISSUE TITLE
Does this plugin works on ST3 ?

### ISSUE THREAD

**Issue by bizoo** [Scopart/GitDiffHelper#4]
I couldn't make it works either by Package Control install or Git clone.
Both have import error when loading.

**Comment by bizoo** [comment]
Sorry but still doesn't works (and don't understand why):

``` python
reloading plugin GitDiffHelper.GitDiffHelper
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\bizoo\AppData\Roaming\Sublime Text 3\Packages\GitDiffHelper\GitDiffHelper.py", line 2, in <module>
    import git
ImportError: No module named 'git'
```

startup, version: 3066 windows x64 channel: dev

**Comment by bizoo** [comment]
I don't think https://github.com/gitpython-developers/GitPython is actually compatible with Python 3.x, am I wrong ?
Replacing "import git" by "from . import git" cause others errors in \git__init__.py

**Comment by Heart1010** [comment]
Have the same error on elementaryOS (based on ubuntu 12.04)

``` python
reloading plugin GitDiffHelper.GitDiffHelper
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/heart/.config/sublime-text-3/Packages/GitDiffHelper/GitDiffHelper.py", line 2, in <module>
    import git
ImportError: No module named 'git'
```

Sublime Text 3 Build 3083

``` bash
~  python --version      
Python 2.7.3
```

**Comment by linibou** [comment]
Right now i haven't got enough time to correct it, i leave it open and will try to fix it soon
